### Arquivo de testes.
GET http://localhost:3000/
Content-Type: application/json

###

GET http://localhost:3000/atividades
Content-Type: application/json

###

GET http://localhost:3000/atividades/5f83532976347714e8f5b770
Content-Type: application/json

###

PUT http://localhost:3000/atividades/5f83532976347714e8f5b770
Content-Type: application/json

{
  "descricao": "tarefa teste",
  "completa": true
}

###
POST http://localhost:3000/atividades
Content-Type: application/json

{
  "descricao": "tarefa 5",
  "completa": false
}
###
DELETE http://localhost:3000/atividades/5f83563a5bb93114e8b0ee0a
Content-Type: application/json

###

